-- +goose Up
CREATE TABLE chirps(id UUID NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, user_id UUID NOT NULL, BODY TEXT NOT NULL);

ALTER TABLE chirps ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- +goose Down
DROP TABLE chirps;
